### ISSUE TITLE
Can I get this updated to scss?

### ISSUE THREAD

**Issue by aanavaneeth** [Stanko/webpack-babel-react-revisited#1]

**Comment by Stanko** [comment]
Hey, this repo will get updated at some point, but for now take a look here https://github.com/workco/marvin

**Comment by jarnohenneman** [comment]
The marvin is to big of a leap for me (allot of new things got added that I'm not sure how they are connected), unfortunately the comment from James (on your blog) is not working for me.

If there is anything I can help with please let me know 👍

**Comment by Stanko** [comment]
Hey there, you can try following documentation for [sass-loader](https://github.com/webpack-contrib/sass-loader), it should be straight forward to get the basic example working.

**Comment by jarnohenneman** [comment]
Understand, so what I got working at the moment is as followed,,,

 ```
 "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-react-html-attrs": "^2.1.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^0.28.7",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.30.1",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7"
},
```

And in the webpack.config.js

```
{
   test: /\.sass$/,
   loader: extractTextPlugin.extract({
      use: [
         'css-loader',
         'sass-loader',
      ]
   }),
},
```

This results in my components having an import too the sass file, import '../../css/footer.sass';

SideQuestion: Is there a work around to not have ../../ slashes in front? Some solution that is more reboost?

**Comment by Stanko** [comment]
What I usually do is to import all sass files into `app.scss` and then just import `app.scss` once in the `index.js`. 

Or you can use [absolute path resolving](https://stanko.github.io/setting-up-webpack-babel-and-react-from-scratch/#absolute-path-resolving) (that is my old webpack 1 post, but the setup is the same).
